### ISSUE TITLE
Route for listing service routes is missing

### ISSUE THREAD

**Issue by BenjaminDobler** [wzr1337/viwiServer#11]
Right now you cannot do http://localhost:3000/media
Expected result would be that it returns a list of available resources for the service e.g.

```json
{
  "status": "ok",
  "data": [
    {
      "name": "renderers",
      "uri": "/media/renderers/"
    },
    {
      "name": "collections",
      "uri": "/media/collections/"
    }
  ]
}
```

PR will follow...

**Comment by wzr1337** [comment]
http://localhost:3000/media2/ should return 404

for an empty service (no resources) an empty list response is expected:

```json
{
  "status": "ok",
  "data": [
  ]
}
```

**Comment by wzr1337** [comment]
implemented,

https://github.com/wzr1337/viwiServer/commit/781eedde1c03fdf1066e7ba7d1e4144985c43d9f 

adds a test accordingly
