### ISSUE TITLE
Revise CORS options and support implementation.

### ISSUE THREAD

**Issue by codeundkakao** [wzr1337/viwiServer#23]
HI, I commented on closed issue #6 already, but I am not sure if this is still tracked, so I just open this new one instead.

I think CORS support is not fully added yet. Indeed the 'corsOpts' object is never actually passed on to cors, leaving the server open to access from all domains while missing to expose the 'Location' header. 

Additionally whitelisting request origins by just checking something like '127.0.0.1' against the request's origin header will not work as the origin header also contains the protocol in use (e.g. http://) and optionally a port, which then need to be in the response as well. Maybe the check can be extended in a way that it returns the request's origin header in full (incl. protocol and port) if it contains a whitelisted IP.

First step should be to pass the corsOpts to cors in expressapp.ts to really expose the Location header and then maybe modify the whitelisting algorithm or change origin to "*" for now.

**Comment by wzr1337** [comment]
can you support here and do the changes? Thanks!

**Comment by codeundkakao** [comment]
Sure, no problem.

**Comment by wzr1337** [comment]
Closed with #26
