### ISSUE TITLE
Error while Transpiling Typescript

### ISSUE THREAD

**Issue by ghost** [wzr1337/viwiServer#40]
**Description:**
Upon building I got an error for
```gulp build```

**Environment:**
macOS Sierra 10.12.5
yarn: 0.24.5
nodejs: v8.0.0ß
repo-branch: master, develop

**Log:**
> XXX-MacBookPro-XXX:viwiServer XXX$ gulp build
> [12:53:24] Using gulpfile ~/XXX/repos/viwiServer/gulpfile.js
> [12:53:24] Starting 'clean'...
> [12:53:24] Starting 'copycdn'...
> [12:53:24] Finished 'copycdn' after 1.81 ms
> [12:53:24] Starting 'copyjson'...
> [12:53:24] Finished 'copyjson' after 1.36 ms
> [12:53:24] Starting 'copyPluginData'...
> [12:53:24] Finished 'copyPluginData' after 581 μs
> [12:53:24] Finished 'clean' after 55 ms
> [12:53:24] Starting 'typescript'...
> src/plugins/media/index.ts(4,25): error TS7016: Could not find a declaration file for module 'stupid-player'. '/XXX/repos/viwiServer/node_modules/stupid-player/index.js' implicitly has an 'any' type.
> [12:53:27] TypeScript: 1 semantic error
> [12:53:27] TypeScript: emit succeeded (with errors)
> [12:53:27] Finished 'typescript' after 2.41 s
> [12:53:27] Starting 'build'...
> [12:53:27] Finished 'build' after 37 μs

**Comment by wzr1337** [comment]
There is no stupid-player definition yet... Would be cool if you could add one..

This is of course an error to be fixed, but the software will still run smoothly

**Comment by wzr1337** [comment]
fixed with 80238435d2cce6c05727d01cbcea0fa180c58f56
