### ISSUE TITLE
Support for $expand field

### ISSUE THREAD

**Issue by BenjaminDobler** [wzr1337/viwiServer#42]
When doing get requests the viwi protocol supports the $expand parameter but this is curently
not supported by the rsiServer. 

One natural way where this could be handled would be the getResource
method of the Resource interface so it looks something like this:
`getResource?(offset?:string|number, limit?:string|number, expand?:number):CollectionResponse;`
This way the plugin would be responsible to expand it`s own resources. 

One issue i see is that sometimes those resources could contain references to elements of other resources which are not directly (by id) accessible. Would it make sense to have a "global" registry where each plugin registers the elements it contains and others can use this to get the full definition of the element by id?
This way the expand functionality could also be handled outside of the plugin so not every plugin would have to rebuild this functionality on it`s own.

One other option would be that every plugin exposes it`s elements (in form of an id-element map) then one could also scan each plugin to find any element by id.

**Comment by BenjaminDobler** [comment]
While digging deeper i think i can already do that with the resources array of the services.
So i would suggest handling expand in the index.ts just like filterByKeys. Hope to have a PR soon...

**Comment by wzr1337** [comment]
*thumbsup*


please consider that $expand can also be a property name, not only a number

`..?$expand=logos`would expand ONLY the logos property on a certain element

**Comment by wzr1337** [comment]
closed with #45
