### ISSUE TITLE
Corporate Proxy blocking git:// urls

### ISSUE THREAD

**Issue by Kiessar** [wzr1337/viwiServer#43]
npm install failed with:

> 1368 silly fetchPackageMetaData error for node-mpg123-util@git://github.com/kicumkicum/node-mpg123-util.git#ae4d215 exited with error code: 128
1369 silly fetchPackageMetaData error for lame@git://github.com/TooTallNate/node-lame.git#596ce2957ed60250cf26b914608f4be75319294a exited with error code: 128
1370 verbose stack Error: exited with error code: 128
1370 verbose stack     at ChildProcess.onexit (D:\programme\nodejs\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
1370 verbose stack     at emitTwo (events.js:125:13)
1370 verbose stack     at ChildProcess.emit (events.js:213:7)
1370 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
1371 verbose cwd D:\Projekte\viwi-server\rsiServer
1372 verbose Windows_NT 6.1.7601
1373 verbose argv "D:\\programme\\nodejs\\node.exe" "D:\\programme\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1374 verbose node v8.1.2
1375 verbose npm  v5.0.3
1376 error exited with error code: 128
1377 verbose exit [ 1, true ]

Corporate Proxy can't resolve git URLS.

Solution is to force git to use https instead of git in URLSs:
`git config --global url."https://".insteadOf git://`

**Comment by wzr1337** [comment]
Yes, when I am behind my corporate proxy, I also have to use this setting.

`git config --global url."https://".insteadOf git://`

you `~/.gitconfig` or the local `.gitconfig` in the current working directory shall end up containing the following lines:

```
[url "https://"]
        insteadOf = git://
```


Thanks for posting!
