### ISSUE TITLE
Add all items from data folder to /medialibrary/tracks/ 

### ISSUE THREAD

**Issue by floki-92** [wzr1337/viwiServer#49]
The rsp.medialibrary plugin holds a `/data/` folder which shall contain a few tracks (*.mp3)

1. A few Copyright free tracks need to be added
2. The folder has to be scanned on startup and all files in the folder have to be added to the /medialibrary/tracks resource

**Comment by wzr1337** [comment]
Later on, we also need to scan Folders and thumbdrives etc. during runtime.. but this would end up in a new issue..

Thanks for raising the issue!

**Comment by wzr1337** [comment]
media moved out, yet implemmented
