### ISSUE TITLE
Shuffle a collection

### ISSUE THREAD

**Issue by floki-92** [wzr1337/viwiServer#52]
A collection in /media/collections/ shall be shuffled and stored as a new collection. The reference in media/renderers/<uuid> needs to be updated with the new (shuffled) collection reference. The old collection will remain for as long as the shuffling is active. Both collections will be present at the same time.

**Comment by wzr1337** [comment]
How will we notice that the one collection is a shuffled copy of the other? There is no flag or reference indicating that? any opinions?

**Comment by wzr1337** [comment]
media moved out
