### ISSUE TITLE
RSI Server Application for Mac

### ISSUE THREAD

**Issue by atvaltechnilesh** [wzr1337/viwiServer#58]
Hi there,

we develop using operating system "mac". It will be very useful, if you could create a mac application for your RSI Server.

Thank you,
Nilesh

**Comment by wzr1337** [comment]
Hi @atvaltechnilesh I also code on the a Mac. The entire software is fully compatible and just needs to be run as it is ;) Let me know if you need support

**Comment by atvaltechnilesh** [comment]
Hi @wzr1337, I mean, if you have an executable program like "exe" for windows. Do you have a programm file that I can install on my mac? Thanks for your quick response.

I dont know how to run. Could you please help me running it?

**Comment by wzr1337** [comment]
@atvaltechnilesh you need to have node installed. You get node here:

https://nodejs.org/en/

once you have it installed, you can easily follow the steps described in https://github.com/wzr1337/rsiServer/blob/master/README.md
