### ISSUE TITLE
What is the difference between rsiServer and the windows programme "RSI Editor"?

### ISSUE THREAD

**Issue by atvaltechnilesh** [wzr1337/viwiServer#59]
Hi there,

What is the difference between rsiServer and the windows programme "RSI Editor"?

RSI Editor is running on windows.

Can you please tell me the difference?

Thank you,
Nilesh

**Comment by wzr1337** [comment]
The RSIServer is a reference server application, build for everyone to use, extend and contribute. It runs a simulation server to teach the API.

The RSI Editor is NOT a public tool.
