### ISSUE TITLE
Improve Plugin discovery/loading

### ISSUE THREAD

**Issue by BenjaminDobler** [wzr1337/viwiServer#62]
Right now each plugin exports its class as 
export {WhateverPluginClass as Service}
This was needed because the PluginLoader does not know what type the Plugin is. All it knows is that it is a service. So it can just require the file and do:
```
const _plugin = require(directory);
service = new _plugin.Service();

```
As an improvement we should have a more explicit way of exporting plugin classes. By convention i suggest that each plugin index.ts exports a `getPlugins():Array<Service>` method which returns an array of Plugin classes. This way one plugin can export one or more plugins.
Each plugin index.ts should also export its plugin classes. As an example this is what the exports for the medialibrary plugin would look like:

```
const getPlugins = ():Array<any> => {
    return [Medialibrary];
}

export { Medialibrary, getPlugins };
```

This gives the opportunity to also normally add plugins from npm packages without the plugin loader. Like this:

> import { Medialibrary } from '@rsi-plugins/medialibrary';
> 
> const server: RsiServer = new RsiServer();
> const medialibrary: Medialibrary = new Medialibrary();
> server.addService(medialibrary);

So all options are there!

What do you think?

Branches to check out the changes are here:
https://github.com/wzr1337/rsi.server/tree/feature/pluginloader
https://github.com/wzr1337/rsi.demo/tree/feature/addbyimport_example
https://github.com/wzr1337/rsi-plugins.medialibrary/tree/getplugins

Pull request if fine will follow

**Comment by wzr1337** [comment]
We should define a "plugin" interface in @rsi/core that enforces every plugin to export the services and the getPlugin() method

https://github.com/wzr1337/rsi.core/blob/master/src/rsiPlugin.ts

**Comment by wzr1337** [comment]
after that, lets go and file a PR ;)

+1

**Comment by BenjaminDobler** [comment]
@wzr1337 How do you define an interface for a module? Any pointers?

**Comment by wzr1337** [comment]
Done ;)
