### ISSUE TITLE
handle ECONNRESET gracefully

### ISSUE THREAD

**Issue by wzr1337** [wzr1337/viwiServer#78]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)

**Comment by wzr1337** [comment]
fixed: https://github.com/wzr1337/rsi.server/tree/0.2.2

**Comment by ghost** [comment]
console.log, why not console.error?

**Comment by wzr1337** [comment]
Should be rather this.logger.error()

We must be aware of scope change when the handler is called... 'This' will
point to the websocket itself

Be aware when you PR 😜
-- 
- Patrick (Mobile)

**Comment by ghost** [comment]
I guess TS supports .bind() to tame the `this` beast ;-)

**Comment by wzr1337** [comment]
Go for it :D


Easy catch
-- 
- Patrick (Mobile)
